default: &default
  adapter: mysql2
  encoding: utf8
  username: prison
  password: legendEDP02
 # username: root
 # password: 12345
  pool: 5
  port: 3306

development:
  <<: *default
  # host: 10.10.10.2
  host: 123.57.7.159
  # host: 10.10.10.114
  # socket: /tmp/mysql.sock
  # socket: /var/mysql.sock
  database: prison_development_mri

production:
  <<: *default
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
  database: prison_production
